export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_REST = "USER_REGISTER_REST";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const REST_USER_FLAGS = "REST_USER_FLAGS";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const FILTER_USERS_TYPE = "FILTER_USERS_TYPE";
export const REST_USER_FILTER = "REST_USER_FILTER";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const REMOVE_USER = "REMOVE_USER";

export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL";
export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";
export const FORGET_PASSWORD_RESET = "FORGET_PASSWORD_RESET";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_RESET = "RESET_PASSWORD_RESET";
export const RESET_DELETE_USER = "RESET_DELETE_USER";

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const MERCHANT_REGISTER_FAIL = "MERCHANT_REGISTER_FAIL";
export const MERCHANT_REGISTER_REQUEST = "MERCHANT_REGISTER_REQUEST";
export const MERCHANT_REGISTER_SUCCESS = "MERCHANT_REGISTER_SUCCESS";
export const MERCHANT_REGISTER_REST = "MERCHANT_REGISTER_REST";

export const MERCHANT_GET_REQUESTS_REQUEST = "MERCHANT_GET_REQUESTS_REQUEST";
export const MERCHANT_GET_REQUESTS_SUCCESS = "MERCHANT_GET_REQUESTS_SUCCESS";
export const MERCHANT_GET_REQUESTS_FAIL = "MERCHANT_GET_REQUESTS_FAIL";

export const MERCHANT_DEAL_REQUEST = "MERCHANT_DEAL_REQUEST";
export const MERCHANT_DEAL_FAIL = "MERCHANT_DEAL_FAIL";
export const MERCHANT_DEAL_SUCCESS = "MERCHANT_DEAL_SUCCESS";
export const MERCHANT_DEAL_RESET = "MERCHANT_DEAL_REST";

export const UPDAT_ME_SUCCESS = "UPDAT_ME_SUCCESS";

export const JOIN_MAZAD_SUCCESS = "JOIN_MAZAD_SUCCESS";

export const INTEREST_MAZAD_SUCCESS = "INTEREST_MAZAD_SUCCESS";
