export const GET_MAZAD_SUCCESS = "GET_MAZAD_SUCCESS";
export const UPDATE_MAZAD_SUCCESS = "UPDATE_MAZAD_SUCCESS";
export const GET_HOME_AUCTION_NOW_SUCCESS = "GET_HOME_AUCTION_NOW_SUCCESS";
export const GET_HOME_AUCTION_UP_COMING_SUCCESS =
  "GET_HOME_AUCTION_UP_COMING_SUCCESS";
